FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# writer script clone
COPY google_cloud_writer.py .
#runner command
CMD ["python", "google_cloud_writer.py"]
