FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Clone of  streamer script
COPY streamer.py .
#runner comand
CMD ["python", "streamer.py"]
